# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'sensmove' do
       pod 'Alamofire', '~> 1.1'
end

target 'sensmoveTests' do
       pod 'Alamofire', '~> 1.1'
end

