# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'POCCharts' do
	pod 'ReactiveCocoa', '~> 2.3'
    pod 'PNChart', '~> 0.8.3'
end

target 'POCChartsTests' do
	pod 'ReactiveCocoa', '~> 2.3'
    pod 'PNChart', '~> 0.8.3'
end

