# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'POC_PNChart' do
	pod 'ReactiveCocoa', '~> 2.3'
end

target 'POC_PNChartTests' do
    pod 'ReactiveCocoa', '~> 2.3'

end

