# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'app' do
       pod 'Alamofire', '~> 1.1'
end

target 'appTests' do
       pod 'Alamofire', '~> 1.1'
end

