Sensmove\AdminBundle\Entity\User:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        isPro:
            type: boolean
            column: is_pro
        email:
            type: string
            length: 255
        password:
            type: string
            length: 255
        haveDevice:
            type: boolean
            column: have_device
    lifecycleCallbacks: {  }
